[window]
padding = { x = 2, y = 3 }
opacity = 0.5
blur = true
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "regular" }

[terminal.shell]
program = "/usr/bin/fish"
args = ["--login"]
